### ISSUE TITLE
1.0.1 not available through pip

### ISSUE THREAD

**Issue by frisellcpl** [klarna/kco_python#3]
Hi,

Could you please make v. 1.0.1 available thorugh pip?

https://pypi.python.org/pypi/KlarnaCheckout/1.0.0

It would simplify my deployment procedures somewhat and I really need the useragent fix you applied in that version. 

Cheers,
Johan

**Comment by keis** [comment]
Sorry about that. it's uploaded now

**Comment by frisellcpl** [comment]
Something didnt work out as planned :) 

Downloading KlarnaCheckout-1.0.1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-546fav31/klarnacheckout/setup.py", line 9, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-546fav31/klarnacheckout/setup.py", line 9, in <module>
    
        long_description=open('README.md').read(),
    
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

**Comment by keis** [comment]
ack. just noticed that removing that package for. need to add a manifest to get the readme included.

**Comment by keis** [comment]
got a 1.0.2 up now. could you give that a spin?

**Comment by frisellcpl** [comment]
:) Just tell me when you are done and I'll test it out.

**Comment by frisellcpl** [comment]
Worked like a charm!
