### ISSUE TITLE
KCO v3 compatible version?

### ISSUE THREAD

**Issue by jacobsvante** [klarna/kco_python#6]
This isn't KCO v3 compatible yet, right? When can we expect that?

**Comment by keis** [comment]
Hi. There is no support for KCOv3 in this library and I don't think there's any specific plans on when there might be one that supports that.

Thankfully the v3 api does not use a custom digest so I think you will be perfectly fine using [requests](http://docs.python-requests.org/en/latest/) or [aiohttp](http://aiohttp.readthedocs.org/en/stable/)

**Comment by jacobsvante** [comment]
@keis I noticed that. Plain usage of requests works just fine. Now let's just hope that we can get a more up-to-date documentation online :wink:
